parameters:
    oro_product.entity.component_product.class: Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct

services:
    oro_product.api.create.component_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@security.authorization_checker'
            - '@oro_security.acl.group_provider.chain'
            - ['VIEW', 'EDIT']
            - ['oro_component_products_edit']
        tags:
            - { name: oro.api.processor, action: create, group: security_check, class: '%oro_product.entity.component_product.class%', priority: 100}

    oro_product.api.delete.component_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@security.authorization_checker'
            - '@oro_security.acl.group_provider.chain'
            - ['EDIT']
            - ['oro_component_products_edit']
        tags:
            - { name: oro.api.processor, action: delete, group: security_check, class: '%oro_product.entity.component_product.class%', priority: 100}
            - { name: oro.api.processor, action: delete_list, group: security_check, class: '%oro_product.entity.component_product.class%', priority: 100}

    oro_product.api.get.component_product.security_check:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemSecurityCheck
        arguments:
            - '@security.authorization_checker'
            - '@oro_security.acl.group_provider.chain'
            - ['VIEW']
            - ['oro_component_products_edit']
        tags:
            - { name: oro.api.processor, action: get, group: security_check, class: '%oro_product.entity.component_product.class%', priority: 100}
            - { name: oro.api.processor, action: get_list, group: security_check, class: '%oro_product.entity.component_product.class%', priority: 100}


    oro_product.api.create.add_component_product:
        class: Oro\Bundle\ProductBundle\Api\Processor\Create\AddRelatedProduct
        arguments:
            - '@oro_product.related_item.component_product.assigner_database_strategy'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: '%oro_product.entity.component_product.class%', priority: 100}

    oro_product.api.get.component_product.acl_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\RelatedItemAclCheck
        arguments: ['@oro_api.entity_serializer.doctrine_helper']
        tags:
            - { name: oro.api.processor, action: get, group: build_query, class: '%oro_product.entity.component_product.class%', priority: -200}
            - { name: oro.api.processor, action: get_list, group: build_query, class: '%oro_product.entity.component_product.class%', priority: -200}

    oro_product.api.delete.component_product.build_single_item_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\BuildSingleItemQuery
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.criteria_connector'
            - '@oro_api.entity_id_helper'
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.component_product.class%', priority: 10 }

    oro_product.api.delete.component_product.load_entity_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadEntityByOrmQuery
        arguments:
            - '@oro_entity.query_hint_resolver'
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.component_product.class%', priority: 0 }

    oro_product.api.delete.component_product.acl_query:
        class: Oro\Bundle\ProductBundle\Api\Processor\Delete\RelatedItemAclCheck
        arguments: ['@oro_api.entity_serializer.doctrine_helper']
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, class: '%oro_product.entity.component_product.class%', priority: 5}
            - { name: oro.api.processor, action: delete_list, group: build_query, class: '%oro_product.entity.component_product.class%', priority: -200}
